# Generated by Django 4.0.5 on 2022-08-05 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='profilepic',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
