# Generated by Django 4.0.5 on 2022-08-07 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0003_alter_person_profilepic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='profilepic',
        ),
    ]
