# Generated by Django 4.0.5 on 2022-08-07 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0004_remove_person_profilepic'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='user',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
