# Generated by Django 4.0.5 on 2022-08-07 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0007_alter_blog_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='user',
            new_name='user_type',
        ),
    ]
