# Generated by Django 4.0.5 on 2022-08-07 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0008_rename_user_blog_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='user_type',
        ),
    ]
